import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fixture } from './helpers.js';
import { lifecycle } from '../memory/lifecycle-fixture.js';
import { scope, seed, NOW } from '../memory/sqlite-fixture.js';
import { SqliteMemoryStore, CONFIRMED_RETENTION } from '../../memory/sqlite-store.js';
import { confirmedInvitationPolicy } from '../../companion/invitations.js';
import { SqliteManagementMemoryPort } from '../../memory/management-port.js';
import { ManagementSettingsStore } from '../../management/settings-store.js';
import { ManagementRuntime } from '../../management/runtime.js';
import { startManagementServer } from '../../management/server.js';
import type { MemoryDynamicsSnapshot, MemoryPolicyPreview } from '../../contracts/memory-dynamics.js';

test('HTTP dynamics uses real isolated SQLite; pure views, forward policy, conflict and honest forget failure',async t=>{
 const f=await fixture(t);await mkdir(join(f.c.projectRoot,'ui'));
 const store=new SqliteMemoryStore({filename:f.c.database,retention:CONFIRMED_RETENTION,invitations:confirmedInvitationPolicy('Asia/Shanghai'),clock:()=>NOW});t.after(()=>store.close());seed(store);
 const memory=new SqliteManagementMemoryPort(store,lifecycle(store)),settings=await ManagementSettingsStore.open(join(f.c.projectRoot,'settings.json'),f.c),runtime=new ManagementRuntime(f.c.sourceRevision);
 const server=await startManagementServer({uiRoot:join(f.c.projectRoot,'ui'),settings,memory,snapshot:()=>({apiVersion:1,runtime:runtime.identity(),modules:runtime.modules(),events:[],settings:settings.snapshot(),adapters:[],credentials:[],characters:memory.characters()})});t.after(()=>server.close());
 const headers={Authorization:'Bearer '+server.token,Origin:server.origin,'Content-Type':'application/json'};
 const get=(p:string)=>fetch(server.origin+p,{headers});
 const send=(p:string,body:unknown,method='POST')=>fetch(server.origin+p,{method,headers,body:JSON.stringify(body)});
 assert.equal((await fetch(server.origin+'/api/memory/dynamics?characterId=companion')).status,401);
 const rev=store.revision(scope());
 const s=await(await get('/api/memory/dynamics?characterId=companion&state=all')).json() as MemoryDynamicsSnapshot;
 assert.ok(s.items.some(x=>x.record.id==='job'));assert.equal(s.dataRevision,rev);
 const p={characterId:'companion',query:'海风公司',evaluatedAt:'2026-10-06T12:00:00Z',expectedDataRevision:s.dataRevision,expectedPolicyRevision:s.policy.revision,policy:{...s.policy.policy,baseHalfLifeDays:60}};
 const preview=await send('/api/memory/preview',p);assert.equal(preview.status,200);
 const result=await preview.json() as MemoryPolicyPreview;assert.equal(result.kind,'preview');assert.ok(result.after[0]!.activation>result.before[0]!.activation);
 assert.equal(store.revision(scope()),rev);assert.equal(store.recall.traces({characterId:'companion',offset:0,limit:10}).total,0);
 assert.equal((await send('/api/memory/policy',{characterId:'companion',expectedRevision:1,operationId:'invalid',policy:{...p.policy,emotionWeight:1}},'PUT')).status,400);
 const save={characterId:'companion',expectedRevision:1,operationId:'save',policy:p.policy};
 assert.equal((await send('/api/memory/policy',save,'PUT')).status,200);
 assert.equal((await send('/api/memory/policy',save,'PUT')).status,200);
 assert.equal((await send('/api/memory/policy',{...save,operationId:'stale'},'PUT')).status,409);
 assert.equal((await send('/api/memory/preview',p)).status,409);
 const version=store.inspect(scope(),'job')!.version;
 const failed=await send('/api/memory/forget',{characterId:'companion',id:'job',expectedVersion:version,operationId:'forget',reason:'synthetic user request'});
 assert.equal(failed.status,400);assert.match(await failed.text(),/来源/);assert.equal(store.inspect(scope(),'job')!.state,'active');assert.equal(store.revision(scope()),rev);
 assert.equal((await send('/api/memory/policy/rollback',{characterId:'companion',expectedRevision:2,targetRevision:1,operationId:'rollback'})).status,200);
 assert.equal(store.dynamics.policy().revision,3);assert.equal(store.inspect(scope(),'job')!.state,'active');
});
